# Generated by Django 5.1.3 on 2024-11-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_alter_customer_first_name_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
